version: '2'
networks:
  bridge:
    driver: bridge

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGODB_USER: cy-world
      MONGODB_PASS: cygcyg123
    volumes:
      - mongodb/db:/data/db
      - mongodb/configdb:/data/configdb
    ports:
      - '27017:27017'

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    links:
      - 'mongodb:mongo'
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: cy-world
      ME_CONFIG_BASICAUTH_PASSWORD: cygcyg123
volumes:
  mongodb:
    driver: local
