development:
  clients:
    default:
      database: <%= ENV['DATABASE_NAME'] %>
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: <%= ENV['DATABASE_NAME'] %>
      hosts:
        - localhost:27017

production:
  clients:
    default:
      database: <%= ENV['DATABASE_NAME'] %>
      hosts:
        - localhost:27017
